version: '3'

volumes:
  psql: # creates a volume called psql that will store your data

services:
  psql:
    image: postgres # this uses the 'latest' version
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password # only do this in development, change to something more secure
    volumes:
      - psql:/var/lib/postgresql/data # saves your data between restarts
    ports:
      - 5555:5432 # binds port 5555 on your computer to the postgres port inside of the container